# https://matsuand.github.io/docs.docker.jp.onthefly/compose/compose-file/compose-file-v3/
version: '3.9'
services:
  db:
    # https://hub.docker.com/_/postgres/
    image: postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=test_db
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_volume:
